environment: &environment
  working_directory: ~/search-guard-kibana-plugin

version: 2

jobs:
  build:
    working_directory: ~/search-guard-kibana-plugin
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Build plugin
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash > /dev/null 2>&1
            export NVM_HOME=~/.nvm
            export MAVEN_HOME=/opt/apache-maven
            ./build.sh 6.4.0 16-SNAPSHOT install
workflows:
  version: 2
  build:
    jobs:
      - build
