version: 2
jobs:
  build:
    working_directory: ~/circleci-sg
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run:
          name: Install nvm
          command: 'curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash'
      - checkout
      - run:
          name: Build plugin
          command: |
            #set -x
            #set +e

            PLUGIN_NAME=searchguard-kibana
            KIBANA_VERSION=6.0.0-rc1
            echo "Building $PLUGIN_NAME-$KIBANA_VERSION.zip"
            DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
            cd "$DIR"
            mkdir -p build_stage
            cd build_stage
            git clone https://github.com/elastic/kibana.git || true
            cd "kibana"
            git fetch
            git checkout "tags/v$KIBANA_VERSION"

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

            nvm install "$(cat .node-version)"
            cd "$DIR"
            rm -rf build/
            rm -rf node_modules/
            #npm install --save hapi@16.0.1
            npm install
            COPYPATH="build/kibana/$PLUGIN_NAME"
            mkdir -p "$COPYPATH"
            cp -a "$DIR/index.js" "$COPYPATH"
            cp -a "$DIR/package.json" "$COPYPATH"
            cp -a "$DIR/lib" "$COPYPATH"
            cp -a "$DIR/node_modules" "$COPYPATH"
            cp -a "$DIR/public" "$COPYPATH"

            mvn -s settings.xml clean deploy