server.host: "0.0.0.0"
elasticsearch.hosts: "https://localhost:9200"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
elasticsearch.ssl.verificationMode: none
elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]
xpack.security.showInsecureClusterWarning: false
telemetry.enabled: false
telemetry.optIn: false
xpack.fleet.agents.enabled: false