stages:
  - Frontend Int Tests


kibana_basicauth:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_basicauth.*"

# kibana_signals_accounts:
#   extends:
#   - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_signals_accounts"

# kibana_signals_accounts_edit:
#   extends:
#     - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_signals_accounts_edit"

# kibana_signals_watches:
#   extends:
#   - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_signals_watches"

# kibana_signals_watches_edit_1:
#   extends:
#     - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_signals_watches_edit_1"

# kibana_signals_watches_edit_2:
#   extends:
#     - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_signals_watches_edit_2"

kibana_saml:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_saml_keycloak.*" 

kibana_oidc:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_oidc_keycloak.*"

kibana_proxy:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_proxy.*"

kibana_jwt:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_jwt.*"

kibana_configui_1:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_configui_1.*" 

kibana_configui_2:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_configui_2.*"  

kibana_configui_3:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_configui_3.*"

kibana_authtokens:
  extends:
  - .be_integration_test
  variables:
    TEST_DEFINITIONS: ".*kibana_authtokens.*"

# kibana_configui_licensehandling:
#   extends:
#   - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_configui_licensehandling.*"

# kibana_kerberos:
#   extends:
#   - .be_integration_test
#   variables:
#     TEST_DEFINITIONS: ".*kibana_kerberos.*"

.be_integration_test:
  allow_failure: false
  stage: "Frontend Int Tests"
  tags:
    - test-large
  rules:
    - if: '$DOCKER_ONLY || $CI_COMMIT_MESSAGE =~ /SKIP-SGI|SKIP-TESTS/'
      when: never

    - if: '$FORCE_SGI || $CI_COMMIT_MESSAGE =~ /FORCE_SGI/ || $CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: always

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"
          || $CI_PIPELINE_SOURCE == "schedule"
          || $CI_COMMIT_TAG =~ /^sg-flx-.*/'
      when: on_success

  image: docker:${DOCKER_VERSION}
  services:
    - docker:${DOCKER_VERSION}-dind
  script:
    - |
       set -e
       set -x
       
       apk add --no-cache sudo git
       sudo sysctl -w vm.max_map_count=262144
       
       echo "Login in into Docker Hub"      
       echo "$DOCKER_PASSWORD" | docker login --username floragunncom --password-stdin docker.io > /dev/null        

       echo "SNAPSHOT_REVISION=$SNAPSHOT_REVISION"
       echo "TEST_DEFINITIONS $TEST_DEFINITIONS"
       
       git clone --depth 1 --branch $IT_BRANCH https://gitlab-ci-token:${CI_JOB_TOKEN}@git.floragunn.com/private/sgi8.git > /dev/null
       cd sgi8/server
       rm -f  docker/kibana/kibana-plugin.zip docker/elasticsearch/search-guard.zip
       

       wget -O docker/elasticsearch/search-guard.zip "$SG_ES_PLUGIN"
       if [[ "${CI_PIPELINE_SOURCE:-}" == "parent_pipeline" ]]; then
          echo "Test was triggered from the parent pipeline,downloading SG_KI_PLUGIN from URL: $SG_KI_PLUGIN"
          wget -O docker/kibana/kibana-plugin.zip "$SG_KI_PLUGIN"
        else
          echo "Using local kibana plugin from target/releases"
          cp "../../target/releases/search-guard-flx-kibana-plugin-${BUILD_VERSION}.zip" \
            docker/kibana/kibana-plugin.zip
       fi  
       ls -lan  
       ./run_test_definition.sh "$TEST_DEFINITIONS"
  artifacts:
    when: always
    paths:
      - sgi8/client/test/testresults**/**/*
    reports:
      junit:
        - "sgi8/client/test/testresults**/junit/Test*.xml"
    expire_in: 30 days